// Package entry point for future consumers (e.g. QuestionDetail.tsx importing
// GraphViewer directly once the question schema grows a `graph` field).
export { default as GraphViewer } from './GraphViewer'
export type { GraphViewerProps } from './GraphViewer'
export { default as TableView } from './TableView'
export type { TableViewProps } from './TableView'
export { default as FigureView } from './FigureView'
export type { FigureViewProps } from './FigureView'
export { parseSpec } from './parser/parseSpec'
export type { Statement, Condition, ParseError, ParseResult } from './parser/types'
export { defaultConfig } from './parser/config'
export type { GraphConfig, GraphBounds, HoverMode, FeaturePointKind } from './parser/config'
export { buildScene } from './scene/buildScene'
export type { SceneOptions } from './scene/buildScene'
export type { Scene, SceneObject, Regression } from './scene/types'
// Space (track 3): the renderer GraphViewer mounts for 3D specs, and the
// kernel that turns parsed statements into its scene.
export { SpaceRenderer } from './space/SpaceRenderer'
export { createSpaceKernel } from './space/kernel/index'
export type { SpaceScene } from './space/scene/types'
export { buildTable } from './scene/buildTable'
export type { NamedTableData } from './scene/buildTable'
export { isThreeD, resolveMode } from './scene/mode'
export type { RenderMode } from './scene/mode'
export { renderFigure } from './figure/render'
export type { FigureResult } from './figure/render'
