// Package entry point for future consumers (e.g. QuestionDetail.tsx importing
// GraphViewer directly once the question schema grows a `graph` field).
export { default as GraphViewer } from './GraphViewer'
export type { GraphViewerProps } from './GraphViewer'
export { default as TableView } from './TableView'
export type { TableViewProps } from './TableView'
export { default as FigureView } from './FigureView'
export type { FigureViewProps, FigureSelection } from './FigureView'
export { parseSpec } from './parser/parseSpec'
export type { Statement, Condition, ParseError, ParseResult } from './parser/types'
export { defaultConfig } from './parser/config'
export type { GraphConfig, GraphBounds, HoverMode, FeaturePointKind } from './parser/config'
export { buildScene } from './scene/buildScene'
export type { Scene, SceneObject, Regression } from './scene/types'
export { buildScene3d } from './scene/buildScene3d'
export type { Scene3D, SceneObject3D } from './scene/types3d'
export { buildTable } from './scene/buildTable'
export type { NamedTableData } from './scene/buildTable'
export { isThreeD, resolveMode } from './scene/mode'
export type { RenderMode } from './scene/mode'
export { renderFigure } from './figure/render'
export type { FigureResult } from './figure/render'
